@startuml Taxi
class Taxi {
    +hailTaxi(): void
    +enterTaxi(): void
    +greetCabbie(): void
    +specifyDestination(): void
    +payCabbie(): void
    +tipCabbie(): void
    +leaveTaxi(): void
}
@enduml
