@startuml DatabaseReader
class DataBaseReader {
    -dbName: String
    -startPostion: int
    +DataBaseReader()
    +DataBaseReader()
    +open(): void
    +close(): void
    +goToFirst(): void
    +goToLast(): void
    +howManyRecords(): int
    +areThereMoreRecords(): boolean
    +positionRecord(): void
    +getRecord(): String
    +getNextRecord(): String
}
@enduml
